### ISSUE TITLE
could u pls give me more details or example code of decryption?

### ISSUE THREAD

**Issue by xcray** [Magalex2x14/LYWSD03MMC-info#1]
how to use the "ADD"(0x11)?
MAC: which 4 bytes to use? low part? the order of the bytes?
what is the "device type" in the nonce? the pdid? for LYWSD03MMC, should it be "5b05"?
and the length of "nonce" is 10 bytes?

thanks a lot for your repo and help!

**Comment by Ernst79** [comment]
In [BLE monitor repo](https://github.com/custom-components/ble_monitor), you can find most of the info. Yesterday, I posted this example on [another topic](https://github.com/custom-components/ble_monitor/issues/289)

```python
from Cryptodome.Cipher import AES

data_string = "043e2b020103000fc4e044ef541f0201061b1695fe58598d0a170fc4e044ef547cc27a5c03a1000000790df258bb"
aeskey = "FDD8CE9C08AE7533A79BDAF0BB755E96"

data = bytes(bytearray.fromhex(data_string))
key = bytes.fromhex(aeskey)

xiaomi_index = data.find(b'\x16\x95\xFE')
xiaomi_mac_reversed = data[xiaomi_index + 8:xiaomi_index + 14]
# xiaomi_mac_reversed: 0fc4e044ef54

device_type = data[xiaomi_index + 5:xiaomi_index + 7]
# device_type: 8d0a

nonce = b"".join([xiaomi_mac_reversed, device_type, data[xiaomi_index + 7:xiaomi_index + 8]])
# nonce: 0fc4e044ef548d0a17

encrypted_payload = data[xiaomi_index + 14:-1]
# encrypted_payload: 7cc27a5c03a1000000790df258

aad = b"\x11"

token = encrypted_payload[-4:]
# token: 790df258

payload_counter = encrypted_payload[-7:-4]
# payload_counter: 000000

nonce = b"".join([nonce, payload_counter])
# nonce: 0fc4e044ef548d0a17000000

cipherpayload = encrypted_payload[:-7]
# cipherpayload: 7cc27a5c03a1

cipher = AES.new(key, AES.MODE_CCM, nonce=nonce, mac_len=4)
cipher.update(aad)

decrypted_payload = cipher.decrypt_and_verify(cipherpayload, token)
# decrypted_payload:  0f0003000000
```

**Comment by Magalex2x14** [comment]
Thank you, @Ernst79 :) 
In addition, this work was used in the implementation of decryption in the [esphome project](https://github.com/esphome/esphome/blob/4f6982fbc5130ad288749ce2386a205ca891e3d6/esphome/components/xiaomi_ble/xiaomi_ble.cpp#L211) (C language).
If these examples are not enough, and there are still questions, then ask them.

**Comment by xcray** [comment]
Thanks for help ,to both of you!
